const DATABASE_NAME = '@gameplay';

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_APPOINMENTS = `${DATABASE_NAME}:appointments`;

export {
    COLLECTION_USERS,
    COLLECTION_APPOINMENTS,
}